pharmacyAutomationSystem/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from drug import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('drugs/',include("drug.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pharmacyAutomationSystem/blog/drug/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "drug"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('adddrug/',views.addDrug,name="adddrug"),
    path('drug/<int:id>',views.detail,name="detail"),
    path('update/<int:id>',views.updateDrug,name="update"),
    path('delete/<int:id>',views.deleteDrug,name="delete"),
    path('',views.drugs,name="drugs"),
]

pharmacyAutomationSystem/blog/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
]

pharmacyAutomationSystem/pharmacyAutomationSystem/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from drugs import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage', views.index),
    path('addDrug' , views.addDrug),
    path('delete/<int:id>',views.delete),
    path('', views.login_view),
    
]

pharmacyAutomationSystem/blog/drug/models.py
from django.db import models


# Create your models here.

class Drug(models.Model):

    title = models.CharField(max_length=50)

    stock = models.CharField(max_length=50)
    quantity = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    
    created_date = models.DateTimeField(auto_now_add=True)
    drug_image = models.FileField(blank = True,null = True,verbose_name="Add Picture")
    def __str__(self):
        return self.title

pharmacyAutomationSystem/blog/user/models.py
from django.db import models

# Create your models here.

pharmacyAutomationSystem/drugs/models.py
from django.db import models

class drug(models.Model):
    name = models.CharField(max_length=50, verbose_name = "product name")
    price = models.PositiveIntegerField(verbose_name="product price")
    stock = models.PositiveIntegerField(verbose_name="product stock")
    quantity = models.PositiveIntegerField(verbose_name="product quantity")
    
    def __str__(self) :
        return self.name

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/drug/models.py
from django.db import models


# Create your models here.

class Drug(models.Model):

    title = models.CharField(max_length=50)

    stock = models.CharField(max_length=50)
    quantity = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    
    created_date = models.DateTimeField(auto_now_add=True)
    drug_image = models.FileField(blank = True,null = True,verbose_name="Add Picture")
    def __str__(self):
        return self.title

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/user/models.py
from django.db import models

# Create your models here.

pharmacyAutomationSystem/blog/drug/forms.py
from django import forms
from .models import Drug

class DrugForm(forms.ModelForm):
    class Meta:
        model = Drug
        fields = ["title","stock","quantity","price","drug_image"]

pharmacyAutomationSystem/blog/user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "User name")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label = "User name")
    password = forms.CharField(max_length=20,label = "Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Confirm Password",widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Do Not Match")
        
        values = {
            "username": username,
            "password": password
        }
        return values

pharmacyAutomationSystem/drugs/forms.py
from unittest.util import _MAX_LENGTH
import django


from django import forms

class loginForm(forms.Form):
    username = forms.CharField(max_length=100, label='username')
    password = forms.CharField(max_length=100, label='password', widget=forms.PasswordInput)

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/drug/forms.py
from django import forms
from .models import Drug

class DrugForm(forms.ModelForm):
    class Meta:
        model = Drug
        fields = ["title","stock","quantity","price","drug_image"]

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "User name")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label = "User name")
    password = forms.CharField(max_length=20,label = "Password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Confirm Password",widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Do Not Match")
        
        values = {
            "username": username,
            "password": password
        }
        return values

pharmacyAutomationSystem/blog/drug/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib import messages
from .models import Drug
from .forms import DrugForm
#from django.contrib.auth.decorators import login_required

# Create your views here.
def drugs(request):
    keyword = request.GET.get("keyword")
    if keyword:
        drugs = Drug.objects.filter(title__contains=keyword)
        return render(request,"drugs.html",{"drugs": drugs})
    drugs = Drug.objects.all()
    
    return render(request,"drugs.html",{"drugs":drugs})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

#@login_required(login_url = "user:login")
def dashboard(request):
    drugs = Drug.objects.filter()
    context = {
        "drugs":drugs
    }
    return render(request,"dashboard.html",context)


def addDrug(request):
    form = DrugForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        drug = form.save(commit=False)
        #drug.author = request.user
        drug.save()

        messages.success(request,"The drug has been successfully created.")
        return redirect("drug:dashboard")
    return render(request,"adddrug.html",{"form":form})
def detail(request,id):
    #drug = Drug.objects.filter(id = id).first()
    drug = get_object_or_404(Drug,id = id)
    return render(request,"detail.html",{"drug":drug})

#@login_required(login_url = "user:login")
def updateDrug(request,id):
    drug = get_object_or_404(Drug,id = id)
    form = DrugForm(request.POST or None,request.FILES or None,instance = drug)
    if form.is_valid():
        drug = form.save(commit=False)
        #drug.author = request.user
        drug.save()

        messages.success(request,"The drug has been successfully updated.")
        return redirect("drug:dashboard")
    return render(request,"update.html",{"form":form})

#@login_required(login_url = "user:login")
def deleteDrug(request,id):
    drug = get_object_or_404(Drug,id = id)
    drug.delete()
    messages.success(request,"The drug was deleted successfully.")
    return redirect("drug:dashboard")

pharmacyAutomationSystem/blog/user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout

# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"You Have Successfully Registered...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

    
    
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Incorrect Username or Password")
            return render(request,"login.html",context)

        messages.success(request,"Signed in Successfully")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
    
def logoutUser(request):
    logout(request)
    messages.success(request,"You Signed Out Successfully...")
    return redirect("index")

pharmacyAutomationSystem/drugs/views.py
from cgi import print_exception
from django.shortcuts import render,redirect ,get_object_or_404
from .models import drug
from django.contrib.auth import authenticate, login
from .forms import loginForm

# Create your views here.
def index(request):
    drugs = drug.objects.all()
    return render(request , "homepage.html",{"drugs":drugs})

def addDrug(request):

    if request.method == "GET":
        return redirect("/homepage")
    else:
       
        Name = request.POST.get("name")
        Price = request.POST.get("price")
        Stock = request.POST.get("stock")
        Quantity = request.POST.get("quantity")
        newDrug = drug(name = Name , price = Price , stock = Stock , quantity = Quantity)

        newDrug.save()
        return redirect("/homepage")

def delete(request , id):
    newDrug = get_object_or_404(drug,id = id)

    newDrug.delete()
    return redirect("/homepage")

def login_view(request):
    form = loginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username , password = password)
        login(request,user)
        return redirect('/homepage')
    return render(request, 'form.html', {'form':form})

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/drug/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib import messages
from .models import Drug
from .forms import DrugForm
#from django.contrib.auth.decorators import login_required

# Create your views here.
def drugs(request):
    keyword = request.GET.get("keyword")
    if keyword:
        drugs = Drug.objects.filter(title__contains=keyword)
        return render(request,"drugs.html",{"drugs": drugs})
    drugs = Drug.objects.all()
    
    return render(request,"drugs.html",{"drugs":drugs})

def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

#@login_required(login_url = "user:login")
def dashboard(request):
    drugs = Drug.objects.filter()
    context = {
        "drugs":drugs
    }
    return render(request,"dashboard.html",context)


def addDrug(request):
    form = DrugForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        drug = form.save(commit=False)
        #drug.author = request.user
        drug.save()

        messages.success(request,"The drug has been successfully created.")
        return redirect("drug:dashboard")
    return render(request,"adddrug.html",{"form":form})
def detail(request,id):
    #drug = Drug.objects.filter(id = id).first()
    drug = get_object_or_404(Drug,id = id)
    return render(request,"detail.html",{"drug":drug})

#@login_required(login_url = "user:login")
def updateDrug(request,id):
    drug = get_object_or_404(Drug,id = id)
    form = DrugForm(request.POST or None,request.FILES or None,instance = drug)
    if form.is_valid():
        drug = form.save(commit=False)
        #drug.author = request.user
        drug.save()

        messages.success(request,"The drug has been successfully updated.")
        return redirect("drug:dashboard")
    return render(request,"update.html",{"form":form})

#@login_required(login_url = "user:login")
def deleteDrug(request,id):
    drug = get_object_or_404(Drug,id = id)
    drug.delete()
    messages.success(request,"The drug was deleted successfully.")
    return redirect("drug:dashboard")

pharmacyAutomationSystem/pharmacyAutomationSystem/blog/user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout

# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"You Have Successfully Registered...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

    
    
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Incorrect Username or Password")
            return render(request,"login.html",context)

        messages.success(request,"Signed in Successfully")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
    
def logoutUser(request):
    logout(request)
    messages.success(request,"You Signed Out Successfully...")
    return redirect("index")

pharmacyAutomationSystem/blog/templates/adddrug.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Add Drug</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Add drug</button>
        </form>
    </div>
  </div>
{% endblock body %}

pharmacyAutomationSystem/blog/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Drug List</h3>

<a class="btn btn-danger" href="{% url 'drug:adddrug' %}">Add drug</a>
<hr>
{% if drugs %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Stock</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for drug in drugs %}
    <tr>
      <th scope="row">{{drug.id}}</th>
      <td><a href="{% url 'drug:detail' drug.id %}">{{drug.title}}</a></td>
      <td><a>{{drug.stock}}</a></td>
      <td><a>{{drug.quantity}}</a></td>
      <td><a>{{drug.price}}</a></td>
      <td><a href="{% url 'drug:update' drug.id %}" class="btn btn-danger">Update</a></td>
      <td><a href="{% url 'drug:delete' drug.id %}" class="btn btn-danger">Delete</a></td>
    </tr>

    {% endfor %}
    <!---<tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>-->

  </tbody>
</table>
{% else %}
<div class="alert alert-danger">
  You don't have drug yet...

</div>
{% endif %}

{% endblock body  %}

pharmacyAutomationSystem/blog/templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h3 class="mt-4">{{drug.title}}</h3>

      <hr>

      <!-- Date/Time -->
      <p>{{drug.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if drug.drug_image %}
      <img class="img-fluid rounded" src="{{drug.drug_image.url}}" width='500' height='500' alt=""> 

      {% endif %}   
      

      <hr>


      <h4>Drug Information:</h4> 
        </div>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Stock</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">{{drug.id}}</th>
            <td><a>{{drug.stock}}</a></td>
            <td><a>{{drug.quantity}}</a></td>
            <td><a>{{drug.price}}</a></td>
          </tr>
      
        </tbody>
      </table>
{% endblock body %}

pharmacyAutomationSystem/blog/templates/drugs.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <h3>Drugs</h3>
            <hr>
            </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Search...">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
      </div>
    </div>

</div>
{% if drugs %}

{% for drug in drugs %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <a href="{% url 'drug:detail' drug.id %}">
                <h2 class="mt-4">{{drug.title}}</h2>
            </a>            


            <!-- Preview Image -->
            {% if drug.drug_image %}
            <a href="{% url 'drug:detail' drug.id %}"><img class="img-fluid rounded" src="{{drug.drug_image.url}}" width="600" height="600" alt=""></a>  

            {% endif %}
            <hr>

            <a style="float:right;" href="{% url 'drug:detail' drug.id %}" class="btn btn-danger">View</a>
            <hr>

        </div>
     </div>
    </div>
    {% endfor %}

    {% else %}
    <div class ="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <div class="alert alert-danger">
                    No Drug Found.

                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endblock body %}

pharmacyAutomationSystem/blog/templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>Pharmacy Automation System</h3>
    <p>Welcome!</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

    <img src="https://www.leighstringer.com/wp-content/uploads/2016/01/stanley-parable-app-awe-web-550x367.jpg" >

    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
    
    <img src="https://qtxasset.com/quartz/qcloud5/media/image/fiercepharma/1599144145/pill_container.jpg/pill_container.jpg?VersionId=rRaYcjgk1cjRGbRbm.3Zm3JfVOYO7E.p"
    width="600" height="400" >
</div>

            
{% endblock body %}

pharmacyAutomationSystem/blog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Pharmacy Automation System</title>
</head>

<body>
    {% include "includes/navbar.html" %}

    <div style="margin-top : 75px; margin-bottom: 50px;" class="container">

        {% if messages %}

            {% for message in messages %}
            {% if message.tags == "info" %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}

            {% endfor %}

        
        {% endif %}
        {% block body %}

        {% endblock body %}

    </div>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>    
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
    
</body>

</html>

pharmacyAutomationSystem/blog/templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Login</button>
        </form>
    </div>
  </div>

{% endblock body %}

pharmacyAutomationSystem/blog/templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Register</button>
        </form>
    </div>
  </div>

{% endblock body %}

pharmacyAutomationSystem/blog/templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Drug</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Update Drug</button>
        </form>
    </div>
  </div>
{% endblock body %}